version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          name: Build binary
          command: make
  release:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
            GO111MODULE=off go get github.com/goreleaser/goreleaser
      - run:
          name: Run goreleaser
          command: goreleaser

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
